// IN CART
export const STALE = 'STALE';

// CHECKOUT PROCESS COMPLETED
export const INITIATED = 'INITIATED';

// BREAKPOINT, IF LENDER DECLINES
export const DECLINED = 'DECLINED';

// ORDER PLACED, IF LENDER ACCEPTS
export const ACCEPTED = 'ACCEPTED';

// LENDER -> WAREHOUSE -> CHECKS -> PACKAGING -> RENTER
export const DROP = 'DROP';

// ON RENT
export const ONRENT = 'ONRENT';

// RENTER -> WAREHOUSE -> CHECKS -> LENDER
export const PICKUP = 'PICKUP';

// DELIVERED TO LENDER, PAYMENT COMPLETED
export const COMPLETED = 'COMPLETED';

// EXTRAS

// EXTENSION REQUESTED
export const EXTENDED = 'EXTENDED';

// ORDER CANCELLED BEFORE COMPLETION
export const CANCELLED = 'CANCELLED';

// REFUNDED MONEY, IF BREAKPOINT BEFORE COMPLETION (CANCELLATION & LENDER DECLINES)
export const REFUNDED = 'REFUNDED';